import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Wrapper from '@/components/Wrapper';
import Background from '@/components/Background';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} bg-black`}>
				<div className='max-w-screen relative h-screen overflow-hidden'>
					<Background />
					<div className='z-[1] grid h-screen w-screen grid-cols-1 grid-rows-[5vh_auto_5vh] bg-primary-500 backdrop-blur-2xl'>
						<Navbar />
						<Wrapper>{children}</Wrapper>
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
